package com.milkstore.service.impl;

import com.milkstore.dto.request.NhomHangRequest;
import com.milkstore.dto.response.NhomHangResponse;
import com.milkstore.entity.NhomChu;
import com.milkstore.entity.NhomHang;
import com.milkstore.exception.ResourceNotFoundException;
import com.milkstore.repository.NhomChuRepository;
import com.milkstore.repository.NhomHangRepository;
import com.milkstore.service.NhomHangService;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
public class NhomHangServiceImpl implements NhomHangService {

    private static final DateTimeFormatter MA_NHOM_HANG_FORMATTER = DateTimeFormatter.ofPattern("ddMMyyHHmmss");
    private static final Sort NEWEST_FIRST = Sort.by(Sort.Direction.DESC, "ngayTao");

    private final NhomHangRepository nhomHangRepository;
    private final NhomChuRepository nhomChuRepository;

    public NhomHangServiceImpl(NhomHangRepository nhomHangRepository, NhomChuRepository nhomChuRepository) {
        this.nhomHangRepository = nhomHangRepository;
        this.nhomChuRepository = nhomChuRepository;
    }

    @Override
    @Transactional(readOnly = true)
    public List<NhomHangResponse> getAll() {
        return nhomHangRepository.findAll(NEWEST_FIRST).stream()
                .map(this::toResponse)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public List<NhomHangResponse> search(String keyword) {
        String cleanKeyword = keyword == null ? "" : keyword.trim();
        if (cleanKeyword.isEmpty()) {
            return getAll();
        }

        return nhomHangRepository
                .findByMaNhomHangContainingIgnoreCaseOrTenNhomHangContainingIgnoreCase(cleanKeyword, cleanKeyword, NEWEST_FIRST)
                .stream()
                .map(this::toResponse)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public NhomHangResponse getByMaNhomHang(String maNhomHang) {
        return toResponse(findByMaNhomHang(maNhomHang));
    }

    @Override
    public NhomHangResponse create(NhomHangRequest request) {
        LocalDateTime now = LocalDateTime.now();
        NhomChu nhomChu = findNhomChu(request.getMaNhomChu());

        NhomHang nhomHang = new NhomHang();
        // MANHOMHANG is generated by backend so users cannot edit it.
        nhomHang.setMaNhomHang(generateMaNhomHang(now));
        nhomHang.setTenNhomHang(cleanText(request.getTenNhomHang()));
        nhomHang.setGhiChu(cleanOptionalText(request.getGhiChu()));
        nhomHang.setNgayTao(now);
        nhomHang.setNhomChu(nhomChu);

        return toResponse(nhomHangRepository.save(nhomHang));
    }

    @Override
    public NhomHangResponse update(String maNhomHang, NhomHangRequest request) {
        NhomHang nhomHang = findByMaNhomHang(maNhomHang);
        NhomChu nhomChu = findNhomChu(request.getMaNhomChu());

        nhomHang.setTenNhomHang(cleanText(request.getTenNhomHang()));
        nhomHang.setGhiChu(cleanOptionalText(request.getGhiChu()));
        nhomHang.setNhomChu(nhomChu);

        return toResponse(nhomHangRepository.save(nhomHang));
    }

    @Override
    public void delete(String maNhomHang) {
        NhomHang nhomHang = findByMaNhomHang(maNhomHang);
        nhomHangRepository.delete(nhomHang);
    }

    private String generateMaNhomHang(LocalDateTime now) {
        String baseCode = now.format(MA_NHOM_HANG_FORMATTER);
        if (!nhomHangRepository.existsById(baseCode)) {
            return baseCode;
        }

        String generatedCode;
        do {
            int suffix = ThreadLocalRandom.current().nextInt(10, 100);
            generatedCode = baseCode + suffix;
        } while (nhomHangRepository.existsById(generatedCode));

        return generatedCode;
    }

    private NhomHang findByMaNhomHang(String maNhomHang) {
        String cleanMaNhomHang = maNhomHang == null ? "" : maNhomHang.trim();
        return nhomHangRepository.findById(cleanMaNhomHang)
                .orElseThrow(() -> new ResourceNotFoundException("Nhom hang not found with MANHOMHANG: " + cleanMaNhomHang));
    }

    private NhomChu findNhomChu(String maNhomChu) {
        String cleanMaNhomChu = maNhomChu == null ? "" : maNhomChu.trim();
        return nhomChuRepository.findById(cleanMaNhomChu)
                .orElseThrow(() -> new ResourceNotFoundException("Nhom chu not found with MANHOM: " + cleanMaNhomChu));
    }

    private NhomHangResponse toResponse(NhomHang nhomHang) {
        NhomHangResponse response = new NhomHangResponse();
        response.setMaNhomHang(nhomHang.getMaNhomHang());
        response.setTenNhomHang(nhomHang.getTenNhomHang());
        response.setGhiChu(nhomHang.getGhiChu());
        response.setNgayTao(nhomHang.getNgayTao());
        if (nhomHang.getNhomChu() != null) {
            response.setMaNhomChu(nhomHang.getNhomChu().getMaNhom());
            response.setTenNhomChu(nhomHang.getNhomChu().getTenNhom());
        }
        return response;
    }

    private String cleanText(String value) {
        return value == null ? null : value.trim().toUpperCase();
    }

    private String cleanOptionalText(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }

        return value.trim();
    }
}
