IF OBJECT_ID('dbo.TB_KHACHHANG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_KHACHHANG (
        MAKHACHHANG VARCHAR(20) NOT NULL PRIMARY KEY,
        TENKHACHHANG NVARCHAR(255) NOT NULL,
        SODT VARCHAR(30) NULL,
        MASOTHUE VARCHAR(50) NULL,
        DIACHI NVARCHAR(500) NULL,
        MAQUANHENGANSACH VARCHAR(50) NULL,
        CCCD VARCHAR(30) NULL,
        NGAYTAO DATETIME2 NULL
    );
END;

IF OBJECT_ID('dbo.TB_NHACUNGCAP', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_NHACUNGCAP (
        MANHACUNGCAP VARCHAR(20) NOT NULL PRIMARY KEY,
        TENNHACUNGCAP NVARCHAR(255) NOT NULL,
        MASOTHUE VARCHAR(50) NULL,
        DIACHI NVARCHAR(500) NULL,
        SODT VARCHAR(30) NULL,
        NHANVIENSALE NVARCHAR(255) NULL,
        NGAYTAO DATETIME2 NULL
    );
END;
