IF OBJECT_ID('dbo.TB_NHOMHANG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_NHOMHANG (
        MANHOMHANG VARCHAR(20) NOT NULL PRIMARY KEY,
        MANHOM VARCHAR(20) NOT NULL,
        TENNHOMHANG NVARCHAR(255) NOT NULL,
        GHICHU NVARCHAR(500) NULL,
        NGAYTAO DATETIME NULL,
        CONSTRAINT FK_TB_NHOMHANG_TB_NHOMCHU
            FOREIGN KEY (MANHOM) REFERENCES dbo.TB_NHOMCHU(MANHOM)
    );
END;

IF COL_LENGTH('dbo.TB_NHOMHANG', 'NGAYTAO') IS NULL
BEGIN
    ALTER TABLE dbo.TB_NHOMHANG ADD NGAYTAO DATETIME NULL;
END;

UPDATE dbo.TB_NHOMHANG
SET NGAYTAO = GETDATE()
WHERE NGAYTAO IS NULL;
