export const menuIconTypes = [
  'settings',
  'unit',
  'customer',
  'supplier',
  'product',
  'product',
  'product',
  'invoice',
  'warehouse',
  'warehouse',
  'invoice',
  'debt',
  'cash',
  'report',
  'help',
]

export const menuRoutes = [
  '/setting',
  '/donvi',
  '/khach-hang',
  '/nha-cung-cap',
  '/nhom-chu',
  '/nhom-hang',
  '/hang-hoa',
  '/products',
  '/inventory',
  '/nhap-kho',
  '/invoices',
  '/debts',
  '/cash',
  '/reports',
  '/help',
]

export const fallbackPageTitles = {
  '/setting': 'Cài đặt',
  '/donvi': 'Quản lý đơn vị tính',
  '/khach-hang': 'Quản lý khách hàng',
  '/nha-cung-cap': 'Quản lý nhà cung cấp',
  '/hang-hoa': 'Quản lý hàng hóa',
  '/products': 'Bảng điều khiển bán hàng',
  '/inventory': 'Quản lý kho hàng',
  '/nhap-kho': 'Nhập kho hàng hóa',
  '/invoices': 'Quản lý hóa đơn',
  '/debts': 'Quản lý công nợ',
  '/cash': 'Quản lý thu chi',
  '/reports': 'Báo cáo',
  '/help': 'Hướng dẫn',
}
